### ISSUE TITLE
Lightmap command does not get filled out properly

### ISSUE THREAD

**Issue by General-101** [Project-Cartographer/H2-Toolkit-Launcher#9]
The lightmap command in the H2 tool kit launcher has an issue where part of it is not filled in properly. This is an issue that can become apparent if the parent folder has a different name from the import file or if a user is attempting to compile multiple BSPs from a single location
By default the launcher will do something like this.
ASS file location: scenarios\solo\cof_sewer\cof_serwer_0.ass

h2tool lightmaps scenarios\solo\cof_sewer\cof_sewer_0 cof_sewer_0 checkerboard
The command that is used should be more like this
h2tool lightmaps scenarios\solo\cof_sewer\cof_sewer cof_sewer_0 checkerboard

To be more specific
h2tool lightmaps scenarios\solo\cof_sewer\(scenario file name) (import file name) checkerboard
The scenario file name is always the same as the parent folder name(In this case it should be "cof_sewer" while the bsp name is the name of the import file(In this case cof_sewer_0 or cof_sewer_1).

Here is a link to two ASS files that can be used to test this.
https://mega.nz/#!Uod3XDgI!w2DWqBVlTTX7j8-og6apTYBAi3jqAExhHMA7LsD_9V4

**Comment by iSupersniper** [comment]
To break this down

h2tool lightmaps scenarios\solo\cof_sewer\cof_sewer cof_sewer_0 checkerboard

h2tool <command> <folderpath> <name_of_ass_file> <lightingquality>
folderpath : scenarios\\<type_of_level>\\<parent_folder_for_tags>\\<scenario_name>

The problem is occurring at 
https://github.com/Project-Cartographer/H2-Toolkit-Launcher/blob/a837e9024f917e4f24b4c56e73ecd6118782ed08/Launcher/MainWindow.xaml.cs#L512 https://github.com/Project-Cartographer/H2-Toolkit-Launcher/blob/a837e9024f917e4f24b4c56e73ecd6118782ed08/Launcher/MainWindow.xaml.cs#L513

At line 512, where you are supposed to set the scenario_name in folderpath, it is being set to level_path, where level_path is being set to the file name without the extension.  

https://github.com/Project-Cartographer/H2-Toolkit-Launcher/blob/a837e9024f917e4f24b4c56e73ecd6118782ed08/Launcher/MainWindow.xaml.cs#L505 https://github.com/Project-Cartographer/H2-Toolkit-Launcher/blob/a837e9024f917e4f24b4c56e73ecd6118782ed08/Launcher/MainWindow.xaml.cs#L506

Then you are setting the name_of_ass_file to the file name without the extension.  Thus having a copy of the .ass file twice rather than the proper folder path.
https://github.com/Project-Cartographer/H2-Toolkit-Launcher/blob/a837e9024f917e4f24b4c56e73ecd6118782ed08/Launcher/MainWindow.xaml.cs#L513

A way to solve this is to get the parent folder path from the .ass file that is the folder before \\\structures\\\ and set that as the first level_path in the arguments in line 512
